modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="spearsmod"
version="${file.jarVersion}"
displayName="Spears"
description='''
Adds spears in versions before their addition to the game!
'''
